### ISSUE TITLE
Canvas Mouse Position Not Correct

### ISSUE THREAD

**Issue by brent-perry** [brent-perry/Mixer-Project#20]
the position of the mouse and where it is drawing does not seem to want to match up with the current mouse, however the code we used before is still the same, so I am not sure what is wrong here.
https://github.com/brent-perry/Mixer-Project/blob/66cee0deba68c9a488cfcc9d449ef857187b0be5/public/js/canvas.js#L23-L56

**Comment by marvinpda** [comment]
I suggest console logging `event` and seeing which other X & Y variables that exist. Try a few different options.

**Comment by brent-perry** [comment]
event.offsetX changed to event.pageX
event.offsetY changed to event.pageY
